"""table user completed field add

Revision ID: 74a809f1bf89
Revises: 599ae63f3f5f
Create Date: 2020-02-05 18:17:18.601050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a809f1bf89'
down_revision = '599ae63f3f5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("todos") as batch_op:
      batch_op.add_column(sa.Column('completed', sa.Boolean, default=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
